version: 2
updates:
  - package-ecosystem: 'npm'
    target-branch: 'develop'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - "@nrkno/sofie-ops"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@nrkno/sofie-ops"
